version: '3.1'

services:
  postgres:
    image: postgres:14.9
    restart: unless-stopped
    environment:
      POSTGRES_DB: "myoayth2_db"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - internal
    ports:
      - "5432:5432"
networks:
  internal:
    name : internal
    driver: bridge
