version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "11:00" # 11am UTC
    ignore:
      # ignore forked linters because of their versioning issues. TODO: fix it.
      - dependency-name: "github.com/golangci/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/build"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/scripts/gen_github_action_config"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: monthly
