name: Run tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run tests
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - run: go test -race -shuffle=on ./...
